plugins {
    id 'java-library'
}

dependencies {
    implementation project(':erp-common')
    implementation project(':erp-domain')

    compileOnly libs.lombok
    annotationProcessor libs.lombok

    implementation 'org.springframework:spring-tx'

    // OAuth2
    api 'org.springframework.boot:spring-boot-starter-security'
    api 'org.springframework.security:spring-security-oauth2-authorization-server'
    api 'org.springframework.boot:spring-boot-starter-oauth2-resource-server'
}