plugins {
    id 'java-library'
}

dependencies {
    implementation project(':erp-common')
    implementation project(':erp-domain')
    implementation project(':erp-application')

    compileOnly libs.lombok
    annotationProcessor libs.lombok
    implementation libs.mapstruct
    annotationProcessor libs.mapstruct.processor
    implementation libs.lombok.mapstruct

    // SQL
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation libs.postgresql

    // MongoDB
    implementation 'org.springframework.boot:spring-boot-starter-data-mongodb'

    // Redis
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
    implementation 'org.springframework.boot:spring-boot-starter-cache'

    // AWS
    implementation libs.aws.s3

    // REST client
    implementation 'org.springframework.boot:spring-boot-starter-web'

    // Mail y HTML
    implementation 'org.springframework.boot:spring-boot-starter-mail'
    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'

    // RabbitMQ
    implementation 'org.springframework.boot:spring-boot-starter-amqp'
}
