plugins {
    id 'org.springframework.boot'
}

dependencies {
    implementation project(':erp-common')
    implementation project(':erp-domain')
    implementation project(':erp-application')
    implementation project(':erp-infrastructure')

    compileOnly libs.lombok
    annotationProcessor libs.lombok
    implementation libs.mapstruct
    annotationProcessor libs.mapstruct.processor
    implementation libs.lombok.mapstruct

    // Web
    implementation 'org.springframework.boot:spring-boot-starter-web'

    // OpenAPI
    implementation libs.springdoc
}
