sequenceDiagram
    autonumber
    participant Client as Cliente
    participant API as "erp-api<br/>QueryCatalogControllerV1<br/>(vars: type:String, catalogType:CatalogType, code:String, response:CatalogView/ItemsView)"
    participant App as "erp-application<br/>FindCatalogByTypeQuery.execute(CatalogType)<br/>FindCatalogItemsByTypeQuery.execute(CatalogType)<br/>FindCatalogItemByCodeQuery.execute(CatalogType, code)"
    participant Domain as "erp-domain<br/>CatalogView / ItemsView (DTOs)<br/>CatalogType (enum)"
    participant Infra as "erp-infrastructure<br/>CatalogRepository"
    participant Common as "erp-common<br/>DTOs / Exceptions (QueryException)"

    Note over API,App: Obtener catálogo por tipo (GET /{type})
    Client->>API: GET /queries/catalogs/{type}
    API->>API: catalogType = CatalogType.valueOf(type.toUpperCase())
    API->>App: FindCatalogByTypeQuery.execute(catalogType)
    App->>Infra: CatalogRepository.findByType(catalogType)
    Infra-->>App: Optional<CatalogView>
    App-->>API: response: CatalogView or throw QueryException
    API-->>Client: 200 OK { CatalogView }

    Note over API,App: Obtener ítems por tipo (GET /{type}/items)
    Client->>API: GET /queries/catalogs/{type}/items
    API->>API: catalogType = CatalogType.valueOf(type.toUpperCase())
    API->>App: FindCatalogItemsByTypeQuery.execute(catalogType)
    App->>Infra: CatalogRepository.findItemsByType(catalogType)
    Infra-->>App: List<ItemsView>
    App-->>API: response: List<ItemsView>
    API-->>Client: 200 OK [ ItemsView... ]

    Note over API,App: Obtener ítem por tipo y código (GET /{type}/items?code=...)
    Client->>API: GET /queries/catalogs/{type}/items?code=ELECTRONICS <br/> GET /queries/catalogs/{type}/items?code={code}
    API->>API: catalogType = CatalogType.valueOf(type.toUpperCase())
    API->>App: FindCatalogItemByCodeQuery.execute(catalogType, code)
    App->>Infra: CatalogRepository.findItemByTypeAndCode(catalogType, code)
    Infra-->>App: Optional<ItemsView>
    App-->>API: response: ItemsView or throw QueryException
    API-->>Client: 200 OK { ItemsView }
